### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://chat.domain.org/api/v4/users/login

### ISSUE THREAD

**Issue by epatpol** [attzonko/mattermost_bot#15]
I don't know if I'm doing anything wrong, but the same config that used to work with the main repo doesn't work with the fork here. Here's the settings I use with it
```python
SSL_VERIFY = True  # Whether to perform SSL cert verification
BOT_URL = 'http://chat.domain.org/api/v4'  # with 'http://' and with '/api/v3' path. without trailing slash. '/api/v1' - for version < 3.0
BOT_LOGIN = 'botmail@domain.com'
BOT_PASSWORD = 'botpassword'
BOT_TEAM = 'botteam'  # possible in lowercase
```

Anything I could try? Thanks!

edit: This might not be related to your fork, but we've updated mattermost recently and I can't really test master for this as it simply doesn't support api/v4 I think.

**Comment by attzonko** [comment]
What version of Mattermost are you running?

**Comment by epatpol** [comment]
Version: 4.7.0

```
Build Hash: 9360131992064203f9ee46fa0504d20276c97339
EE Build Hash: none
Build Date: Thu Feb 15 22:18:28 UTC 2018
```

**Comment by attzonko** [comment]
This seems like an authorization problem. You did check http vs https? Does changing it back to v3 fix the issue?

**Comment by epatpol** [comment]
v3 seems to give the same issue. I used those steps to use your fork. 


- create a virtual environment mmpy_bot_test
python -m venv mmpy_bot_test

- activate the virtual environment
mmpy_bot_test\Scripts\activate

- install attzonko's fork:master
pip install git+https://github.com/attzonko/mattermost_bot.git

then you can test your bot under this virtual environment

As referenced in the PR. Is it possible your latest changes aren't on the master of your fork?

**Comment by attzonko** [comment]
Not possible. I am currently using the master of this fork in our production environment without any issues. 

Can you verify the exact error you are seeing, and if you can access that url manually?

**Comment by seLain** [comment]
@epatpol Could you try this code to see if the same exception is thrown : 

```python
from mattermost_bot.bot import Bot, PluginsManager
from mattermost_bot.mattermost_v4 import MattermostClientv4
from mattermost_bot.dispatcher import MessageDispatcher

SSL_VERIFY = True
BOT_URL = 'http://chat.domain.org/api/v4'
BOT_LOGIN = 'botmail@domain.com'
BOT_PASSWORD = 'botpassword'
BOT_TEAM = 'botteam'  # possible in lowercase
PLUGINS = []

class LocalBot(Bot):

    def __init__(self):
        self._client = MattermostClientv4(
            BOT_URL, BOT_TEAM,
            BOT_LOGIN, BOT_PASSWORD,
            SSL_VERIFY
            )
        self._plugins = PluginsManager(PLUGINS)
        self._dispatcher = MessageDispatcher(self._client, self._plugins)

if __name__ == "__main__":
    LocalBot().run()
```
Be sure you changed `BOT_URL`, `BOT_LOGIN`, and `BOT_PASSWORD` to what they supposed to be.

**Comment by epatpol** [comment]
How am I supposed to run this file? It says it needs `MATTERMOST_BOT_SETTINGS_MODULE`

```
    raise KeyError(key) from None
KeyError: 'MATTERMOST_BOT_SETTINGS_MODULE'
```
What I did was create a test.py file in venv containing your fork, and run python test.py file, with the file containing exactly what you have above. I'm still unsure why this env variable is always needed...

**Comment by epatpol** [comment]
Ok nvm I just copied the env variable in another file in set `MATTERMOST_BOT_SETTINGS_MODULE` to that file. I still get the same error with your code @seLain 

```
Traceback (most recent call last):
  File "/home/user/Projects/Github/matterbot_v4_test/test2.py", line 24, in <module>
    LocalBot().run()
  File "/home/user/Projects/Github/matterbot_v4_test/test2.py", line 18, in __init__
    SSL_VERIFY
  File "/home/user/Projects/Github/matterbot_v4_test/test/lib/python3.5/site-packages/mattermost_bot/mattermost_v4.py", line 92, in __init__
    self.login(team, email, password)
  File "/home/user/Projects/Github/matterbot_v4_test/test/lib/python3.5/site-packages/mattermost_bot/mattermost.py", line 166, in login
    self.user = self.api.login(team, email, password)
  File "/home/user/Projects/Github/matterbot_v4_test/test/lib/python3.5/site-packages/mattermost_bot/mattermost_v4.py", line 29, in login
    response.raise_for_status()
  File "/home/user/Projects/Github/matterbot_v4_test/test/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://chat.domain.org/api/v4/users/login
```

So it might be a problem with our mattermost setup?

If I access this url directly I get a response with 
```
{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"dbd917xsuigqznpbmtzwt3boph","status_code":401}
```

**Comment by seLain** [comment]
@epatpol  The `MATTERMOST_BOT_SETTINGS_MODULE` KeyError will be fixed next update. Before that, you can manually change this code in `site-packages\mattermost_bot\settings.py` :
```python
settings_module = os.environ['MATTERMOST_BOT_SETTINGS_MODULE']
```
to 
```python
settings_module = os.environ.get('MATTERMOST_BOT_SETTINGS_MODULE')
```

Back to your original issue, the code I posted works with correct setting. 
 * If the mattermost server domain name is wrong or the server is done, it raises `ConnectionError`
 * If the API url is wrong, i raises `HTTPError 404 Not found`
 * If the BOT_LOGIN is wrong, it raises `HTTPError 400 Bad request`
 * If the BOT_PASSWORD is wrong, it raises `HTTPError 401  Unauthorized`

Could you double check the password ?

**Comment by epatpol** [comment]
Yea that's weird I already tried the email/password combination manually and it works. I even tried creating a new user with another password and it did the same error.

**Comment by epatpol** [comment]
I tried posting to that url with curl, using the same e-mail/password I have set in the config, and I do receive a token in return... I'm not that good in python but I can try debugging the bot a bit and see if it sends the correct informations I entered in that settings file.

**Comment by epatpol** [comment]
I tried with python 2.7 and python 3.5, I get the same error in both cases, it works perfectly with postman and curl, but trying requests (from python) like `requests.post(url, data)` I get the same 401 error... Very weird...

**Comment by attzonko** [comment]
One debug step you can try is to pretty print the full response you get back from requests.post() before the exception gets raised. You might gleam some helpful info from that.

Another potential debug step is to try and set your SSL_VERIFY to false.

**Comment by epatpol** [comment]
Thanks for the answers guys! AFAIK we use mattermost behind nginx for our reverse proxy to map chat.domain.org to domain.org:8065 (mattermost port mapped to running docker image). I tried the `allow_redirects=False` and got a 301 code, which is also weird I think?

```
result = {Response} <Response [301]>
 _content = {bytes} b'<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor="white">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.13.3</center>\r\n</body>\r\n</html>\r\n'
 _content_consumed = {bool} True
 _next = {PreparedRequest} <PreparedRequest [GET]>
 apparent_encoding = {str} 'ascii'
 connection = {HTTPAdapter} <requests.adapters.HTTPAdapter object at 0x7f2e025954a8>
 content = {bytes} b'<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor="white">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.13.3</center>\r\n</body>\r\n</html>\r\n'
 cookies = {RequestsCookieJar} <RequestsCookieJar[]>
 elapsed = {timedelta} 0:00:05.152662
 encoding = {str} 'ISO-8859-1'
 headers = {CaseInsensitiveDict} {'Content-Type': 'text/html', 'Date': 'Tue, 06 Mar 2018 14:31:36 GMT', 'Content-Length': '185', 'Connection': 'keep-alive', 'Server': 'nginx/1.13.3', 'Location': 'https://chat.domain.org/api/v4/users/login'}
 history = {list} <class 'list'>: []
 is_permanent_redirect = {bool} True
 is_redirect = {bool} True
 links = {dict} {}
 next = {PreparedRequest} <PreparedRequest [GET]>
 ok = {bool} True
 raw = {HTTPResponse} <urllib3.response.HTTPResponse object at 0x7f2e01b1a0f0>
 reason = {str} 'Moved Permanently'
 request = {PreparedRequest} <PreparedRequest [POST]>
 status_code = {int} 301
 text = {str} '<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor="white">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.13.3</center>\r\n</body>\r\n</html>\r\n'
 url = {str} 'http://chat.domain.org/api/v4/users/login'
```

**Comment by seLain** [comment]
How about changing `if response.status_code == 307:` to `if response.status_code in [301, 307]:` again ?

Code 301 means the requested URL has been permanently moved to a new URL.  The new URL should also be specified in `response.headers['Location']`. So I guess we can still try to make a second request.

**Comment by attzonko** [comment]
Do you believe that your nginx is the one responding with the 301? Do you have access to your nginx configuration? Can you post your nginx configuration? Also can you post the full response when you were getting the 401 status code?

**Comment by epatpol** [comment]
I'm not so sure about this @attzonko, I'm not the one who usually tinkers with nginx on our server here, but I can try asking around. Otherwise the fix mentionned by @seLain works for me!

**Comment by attzonko** [comment]
Glad to hear the fix works, I think it also makes sense for us to check for redirect and re-try. @seLain do you want to make a PR with all redirect status codes 301, 302, 307, any others?

**Comment by seLain** [comment]
No problem. I will put together a PR later. Should the PR be sent to working_apiv4 branch, or ?

I learned something new in this case :)

**Comment by attzonko** [comment]
Hmm. I think we should add it to both branches for now. 

Thanks!
Alex

On Mar 6, 2018, at 9:15 AM, Victor Hu <notifications@github.com> wrote:

No problem. I will put together a PR later. Should the PR be sent to working_apiv4 branch, or ?

I learned something new in this case :)

**Comment by epatpol** [comment]
Upon further testing there might be other places where redirect or something along those lines needs to be fixed, I just had the following error
```
Traceback (most recent call last):
  File "/snap/pycharm-community/43/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/snap/pycharm-community/43/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/43/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/43/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "run.py", line 13, in <module>
    Bot().run()
  File "/lib/python3.5/site-packages/mattermost_bot/bot.py", line 36, in run
    self._dispatcher.loop()
  File "/lib/python3.5/site-packages/mattermost_bot/dispatcher.py", line 120, in loop
    'user_added', 'user_removed']):
  File "/lib/python3.5/site-packages/mattermost_bot/mattermost.py", line 193, in messages
    if not self.connect_websocket():
  File "/lib/python3.5/site-packages/mattermost_bot/mattermost.py", line 180, in connect_websocket
    self._connect_websocket(url, cookie_name='MMAUTHTOKEN')
  File "/lib/python3.5/site-packages/mattermost_bot/mattermost.py", line 189, in _connect_websocket
    else ssl.CERT_NONE
  File "/lib/python3.5/site-packages/websocket/_core.py", line 494, in create_connection
    websock.connect(url, **options)
  File "/lib/python3.5/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/lib/python3.5/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "lib/python3.5/site-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 301 Moved Permanently
```

Makes sense that the websocket connection would also need a similar fix no?

**Comment by seLain** [comment]
I really should set up similar environment and reproduce this error ......

Please try to revise `login()` in `site-packages\mattermost_bot\mattermost_v4.py` again :
```python
def login(self, team, account, password):
        props = {'login_id': account, 'password': password}
        response =requests.post(
            self.url + '/users/login',
            data = json.dumps(props),
            verify=self.ssl_verify,
            allow_redirects=False)
!       if response.status_code in [301, 302, 307]:
+           # reset self.url to the new URL
+           self.url = response.headers['Location'].replace('/users/login', '')
            # re-try login if redirected
            response = requests.post(
!                self.url + '/users/login',
                 data = json.dumps(props),
                 verify=self.ssl_verify,
                 allow_redirects=False)
        if response.status_code == 200:
        .....
```
It updates the `MattermostAPIv4.url` when error code 301, 302, or 307 is returned.
The  `MattermostAPIv4.url` will then be used in `MattermostClientv4.connect_websocket()` and other places.

**Comment by epatpol** [comment]
Thanks @seLain it works now! If I get time today I'll try to make a very minimal reproducible setup with docker with nginx and mattermost that you could test if you're interested.

**Comment by attzonko** [comment]
PR with fix merged
